name: Release

on: [push]

jobs:
  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target wasm32-unknown-unknown --release
      - name: Install binaryen
        run: sudo apt-get install binaryen
      - name: Run wasm-opt
        run:  wasm-opt -O2 -o ledger_candid-opt.wasm target/wasm32-unknown-unknown/release/ledger_candid.wasm
